### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by xiaoheiai4719** [czqasngit/objc_msgSend_hook#1]

**Comment by xiaoheiai4719** [comment]
hook_start
ObjCHook(40778,0x16b6ef000) malloc: *** error for object 0x656c646e61: pointer being freed was not allocated
ObjCHook(40778,0x16b6ef000) malloc: *** set a breakpoint in malloc_error_break to debug

**Comment by chenzhengxu** [comment]
`if(_cd->stack_info) free(_cd->stack_info);`偶现的crash，在初始化`common_data`的时候加上`_cd->stack_info = NULL;`应该能解决问题

**Comment by czqasngit** [comment]
是滴,感谢你发现这个问题!~

**Comment by czqasngit** [comment]
我已经修复关提交更新
