### ISSUE TITLE
启动奔溃

### ISSUE THREAD

**Issue by jiangmingz** [czqasngit/objc_msgSend_hook#2]
![image](https://user-images.githubusercontent.com/187824/56579254-4976c900-6602-11e9-9c8a-f4d96842bc05.png)
我觉得是你在before的时候不为0的时候没有释放first对象

**Comment by czqasngit** [comment]
你可以提供一下你的工程吗？我大概知道问题在哪里，需要验证一下.

**Comment by czqasngit** [comment]
我更新了代码 ，你可以测试一下

**Comment by jiangmingz** [comment]
thx

**Comment by jiangmingz** [comment]
@czqasngit 这是公司的项目，不能提供代码，我测试了还是错误的。

**Comment by jiangmingz** [comment]
![image](https://user-images.githubusercontent.com/187824/57291019-362f2780-70f1-11e9-802d-61c32de783fb.png)
我注释掉上面的代码这里也报错了。

**Comment by jiangmingz** [comment]
![image](https://user-images.githubusercontent.com/187824/57291144-71315b00-70f1-11e9-9666-a748358e5277.png)
这是报错是的值
