### ISSUE TITLE
运行报错 ，可以帮忙看下吗

### ISSUE THREAD

**Issue by shizhilya** [czqasngit/objc_msgSend_hook#3]
<img width="810" alt="FAFC8177-8289-45AF-9606-54F511B20612" src="https://user-images.githubusercontent.com/14833970/61270585-ad112c80-a7d4-11e9-8ec5-63d6dc3970db.png">

**Comment by czqasngit** [comment]
这样看不出来问题呢

**Comment by miludan** [comment]
我也遇到一样的问题，看起来是target里的指针指向的内存是不可访问的
