### ISSUE TITLE
为什么要保存x8、x9？

### ISSUE THREAD

**Issue by chenhuafeng** [czqasngit/objc_msgSend_hook#4]
#define save() \
__asm volatile ( \
"stp x8, x9, [sp, #-16]!\n" \
"stp x6, x7, [sp, #-16]!\n" \
"stp x4, x5, [sp, #-16]!\n" \
"stp x2, x3, [sp, #-16]!\n" \
"stp x0, x1, [sp, #-16]!\n" \
);

**Comment by czqasngit** [comment]
ARM64 入参是最多保存8个参数到寄存器,多了的会保存到栈上
如果你去掉X8 X9也是正常的
但通过测试发现X8很多情况都会保存一个class的指针,这里为了避免一些问题就多保存了两个寄存器数据，这样也不受影响
stp一次性操作两个寄存器

**Comment by czqasngit** [comment]
上面是我的理解,当时在查阅资料并且与别人讨论的时候也未发现更好的解释

**Comment by czqasngit** [comment]
x8 is used for struct returns
